version: '3.9'
services:
    app:
        build:
            context: ./
            dockerfile: ./Dockerfile
        volumes:
            - type: bind
              source: ./
              target: /usr/src/app
        command: bash -c "npm run start:dev"
        ports:
            - ${APP_PORT}:${APP_PORT}
        networks:
            - application
    postgres:
        image: postgres:15.1
        volumes:
            - type: volume
              source: postgres-data
              target: /var/lib/postgresql/data
        env_file:
          - .env
        networks:
            - application
    pgadmin4:
        image: dpage/pgadmin4:6.14
        restart: always
        ports:
            - ${PGADMIN4_PORT}:80
        env_file:
            - .env
        networks:
            - application
networks:
    application:
        driver: bridge
volumes:
  postgres-data: